### ISSUE TITLE
feat: different transaction types per position

### ISSUE THREAD

**Issue by faddat** [somatic-labs/meteorite#21]
After implementing the positions feature, we will make it possible to send transactions of different variteies based on the position.

So in a situation where:

```go
positions := 5
```

Hardhat should start, and automatically make transactions that will ensure that the first 5 positions all have balances that don't diverge by more than 10%.

the configuration file will change at this time, too

If there is no per-position configuration, then hardhat will spam from all 5 of the positions configured. 

If there is per-position configuration, then hardhat 

```toml
[position1] 
type = bank_send
node = url1

[position2] 
type = bank_send
node = url1

[position3] 
type = bank_send
node = url1

[position4] 
type = bank_send
node = url1


[position5] 
type = bank_send
node = url1

```

This will allow us to experience fewer sequence mismatches because we will broadcast from multiple accounts at the same time.  It will also allow us to fill blocks more completely, because we will be able to have some positions do big transactions, while others do small transactions. 

 

ref: 

* #20
